global:
  scrape_interval: 500ms  # Set to 0.5 seconds for testing to capture short spikes
  evaluation_interval: 1s

scrape_configs:
  - job_name: 'nats'
    static_configs:
      - targets: ['nats:8222']
    metrics_path: '/metrics'

  - job_name: 'client_metrics'
    static_configs:
      - targets: ['client_metrics:9109']
    metrics_path: '/metrics'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090'] 